# -*- coding: utf-8 -*-
"""DataCo_Product_Analytics_SQL_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4EBgEXC8rhRl8bgbFwxN_sPg9w_nzki
"""

#installing SQL Db and pandas packages
!pip -q install duckdb pandas

#importing the libraries from the packages
import pandas as pd
import duckdb

#load the dataset file
from google.colab import files
uploaded = files.upload()

#check the dataset file is loaded
import os
print(os.getcwd())
print(os.listdir())

df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin1")
df.head()

#find the shape of the dataset to confirm the number of rows and columns
df.shape

#list the columns of the dataset
df.columns.tolist()

#list column names, numbers with data tyeps
df.info()

#Standardizing the column names for python and SQL
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.columns = df.columns.str.replace("-","_")
df.columns.tolist()

#Check for duplicates
df.duplicated().sum()

#convert dates columns to datetime type; errors = 'coerce' will convert bad vaules to null instead of crashing
df['order_date_(dateorders)'] = pd.to_datetime(
    df['order_date_(dateorders)'], errors='coerce'
)

df['shipping_date_(dateorders)'] = pd.to_datetime(
    df['shipping_date_(dateorders)'], errors='coerce'
)

#Numeric and Business data sanity checking
df[['sales','order_item_quantity','product_price','benefit_per_order']].describe()

#Remove Negative Sales data
df = df[df['sales'] >= 0]

#Remove Zero Sales quantities
df = df[df['order_item_quantity'] > 0]

#Check for Null values in key columns
important_cols = [
    'order_id',
    'customer_id',
    'category_name',
    'sales',
    'order_status',
    'shipping_mode'
]
df[important_cols].isnull().sum()

#register the dataframe into Duckdb
import duckdb
con =  duckdb.connect()
con.register("orders", df)

#EDA SQL Queries
#ORDERS
#Revenue and Order Status
#order_details =
con.sql("""
SELECT
  order_status,
  COUNT(DISTINCT order_id) AS total_orders,
  ROUND(SUM(sales),2) AS total_revenue,
  ROUND(AVG(sales),2) AS avg_order_value
FROM orders
GROUP BY order_status
ORDER BY total_revenue DESC
""").df()

#EXPORT SQL OUTPUT TABLE
#CONVERT SQL RESULTS INTO DATAFRAME, AND THEN CONVERT THE DATAFRAME INTO CSV FILE

#order_details.to_csv('order_details.csv', index=False)

#from google.colab import files
#files.download('order_details.csv')

#Top Product Categories
#top_product_category =
con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue
FROM orders
GROUP BY category_name
ORDER BY revenue DESC
LIMIT 10
""").df()

#top_product_category.to_csv('top_product_category.csv', index=False)

#from google.colab import files
#files.download('top_product_category.csv')

#Average Revenue per Order by Category
avg_rev_per_order_category = con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(sales)/COUNT(DISTINCT order_id),2) AS avg_order_value
FROM orders
GROUP by category_name
ORDER BY avg_order_value DESC
""").df()

avg_rev_per_order_category.to_csv('avg_rev_per_order_category.csv', index=False)

from google.colab import files
files.download('avg_rev_per_order_category.csv')

#Profitability by Category
profit_by_category = con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY category_name
ORDER BY profit_margin_percent DESC
""").df()

profit_by_category.to_csv('profit_by_category.csv', index=False)

from google.colab import files
files.download('profit_by_category.csv')

#Categories with High Number of Orders but low margins
high_order_low_margin_products = con.sql("""
SELECT
  category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY category_name
HAVING COUNT(DISTINCT order_id) > 5000
ORDER BY profit_margin_percent ASC
""").df()

high_order_low_margin_products.to_csv('high_order_low_margin_products.csv', index=False)

from google.colab import files
files.download('high_order_low_margin_products.csv')

#Shipping Mode vs Profitability
shipping_mode_profitability = con.sql("""
SELECT shipping_mode,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY shipping_mode
ORDER BY profit_margin_percent ASC
""").df()

shipping_mode_profitability.to_csv('shipping_mode_profitability.csv', index=False)

from google.colab import files
files.download('shipping_mode_profitability.csv')

#Late Delivery risk vs Profitability
late_delivery_risk_profitability = con.sql("""
SELECT
    late_delivery_risk,
    COUNT(DISTINCT order_id) AS orders,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(benefit_per_order),2) AS profit,
    ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percentage
FROM orders
GROUP BY late_delivery_risk
""").df()

late_delivery_risk_profitability.to_csv('late_delivery_risk_profitability.csv', index=False)

from google.colab import files
files.download('late_delivery_risk_profitability.csv')

#RISKS
#Shipping Mode vs Highest Late Risk
con.sql("""
SELECT
    shipping_mode,
    COUNT(DISTINCT order_id) AS orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END)
        * 100.0 / COUNT(DISTINCT order_id), 2
    ) AS risk_rate_percentage
FROM orders
GROUP BY shipping_mode
ORDER BY risk_rate_percentage DESC
""").df()

con.sql("""
SELECT late_delivery_risk, COUNT(*)
FROM orders
GROUP BY late_delivery_risk
""").df()

#Regions with Most Risks
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT order_id) AS orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END)
        * 100.0 / COUNT(DISTINCT order_id), 2
    ) AS risk_rate_percentage
FROM orders
GROUP BY order_region
ORDER BY risk_rate_percentage DESC
LIMIT 10
""").df()

#Risk Impact Score
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(SUM(CASE WHEN late_delivery_risk = 1 THEN sales ELSE 0 END), 2) AS risky_revenue
FROM orders
GROUP BY order_region
ORDER BY risky_revenue DESC
LIMIT 10
""").df()

#Region wise Risk Impact Score
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk=1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk=1 THEN order_id END)
        *100.0 / COUNT(DISTINCT order_id),2
    ) AS risk_rate_percentage,
    ROUND(SUM(CASE WHEN late_delivery_risk=1 THEN sales ELSE 0 END),2) AS risky_revenue
FROM orders
GROUP BY order_region
ORDER BY risky_revenue DESC
LIMIT 5
""").df()

